# -*- coding: utf-8 -*-
"""ITM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vFv5kECw0noFafyNJu8KvX02H2l_mko7
"""

import json

record = {'2021001':{'name':'Smart phone', 'price':25000,'qty':10},
          '2021002':{'name':'Speaker', 'price':15000,'qty':15},
          '2021003':{'name':'PCs', 'price':50000,'qty':7},
          '2021004':{'name':'Laptop', 'price':60000,'qty':20},
          '2021005':{'name':'TV', 'price':50000,'qty':25},
          '2021006':{'name':'Washing Machine', 'price':15000,'qty':5},
          '2021007':{'name':'Oven', 'price':10000,'qty':10},
          '2021008':{'name':'Water purifier', 'price':7000,'qty':10},
          '2021009':{'name':'AC', 'price':25000,'qty':15},
          '2021010':{'name':'Tubelight', 'price':200,'qty':50},
          '2021011':{'name':'LED Bulb', 'price':150,'qty':70},
          '2021012':{'name':'Headphones', 'price':2500,'qty':20},
          '2021013':{'name':'Earphones', 'price':500,'qty':50},
          '2021014':{'name':'Pods', 'price':10000,'qty':10},
          '2021015':{'name':'Air Frier', 'price':9000,'qty':5},
          '2021016':{'name':'Printer', 'price':10000,'qty':4},
          '2021017':{'name':'Scanner', 'price':5000,'qty':10},
          '2021018':{'name':'Flash Drive', 'price':2000,'qty':3},
          '2021019':{'name':'Keyboard', 'price':750,'qty':5},
          '2021020':{'name':'Mouse', 'price':500,'qty':10},
          '2021021':{'name':'Toaster', 'price':2000,'qty':3},
          '2021022':{'name':'Juicer', 'price':3000,'qty':4},
          '2021023':{'name':'Air purifier', 'price':7500,'qty':2},
          '2021024':{'name':'Microwave', 'price':20000,'qty':10},
          '2021025':{'name':'Griller', 'price':2500,'qty':5}}

myrecord=json.dumps(record)

myrecord

fd =open('record.json','w')
fd.write(myrecord)
fd.close()

fd = open('record.json','r')
txt=fd.read()
fd.close()

records=json.loads(txt)

"""# New Section

# **Adding New items to inventory**
"""

prod_id=str(input("Enter the product id : "))
prod_name=str(input("Enter the product name : "))
prod_price=int(input("Enter the product price : "))
prod_qty=int(input("Enter the product qty : "))

record[prod_id]={'name':prod_name,'price':prod_price,'qty':prod_qty}

js=json.dumps(record)

fd=open("record.json",'w')
fd.write(myrecord)
fd.close()

record



prod_id=str(input("Enter the product id : "))
prod_name=str(input("Enter the product name : "))
prod_price=int(input("Enter the product price : "))
prod_qty=int(input("Enter the product qty : "))

record[prod_id]={'name':prod_name,'price':prod_price,'qty':prod_qty}

js=json.dumps(record)

fd=open("record.json",'w')
fd.write(myrecord)
fd.close()

record

fd=open("record.json",'w')
fd.write(myrecord)
fd.close()

myrecord=json.dumps(record)

fd = open('record.json','r')
txt=fd.read()
fd.close()

records=json.loads(txt)

"""# **Updating the quantity of items**"""

fd = open('record2.json','r')
txt=fd.read()
fd.close()

records=json.loads(txt)

records

record

up_prod_id=str(input("Enter the product id:"))
up_prod_qty=int(input("Enter the product quantity:"))

while up_prod_id in record:
  if record[prod_id]['qty']==0:
    print("Out of Stocks!")
  elif record[prod_id]['qty']>= up_prod_qty:
    record[prod_id] ['qty']=record[prod_id]['qty']-up_prod_qty  
  else:
    "Product is not Available"

myrecord=json.dumps(record)

fd=open("record2.json",'w')
fd.write(myrecord)
fd.close()

record[prod_id]['qty']

up_prod_id=str(input("Enter the product id:"))
up_prod_qty=int(input("Enter the product quantity:"))

record[up_prod_id]['qty']

if record[up_prod_id]['qty']==0:
  print("Out of Stocks!")
elif record[up_prod_id]['qty']>= up_prod_qty:
  record[up_prod_id] ['qty']=record[up_prod_id]['qty']-up_prod_qty  
else:
  "Product is not Available"

up_prod_id=str(input("Enter the product id:"))
up_prod_qty=int(input("Enter the product quantity:"))

if record[up_prod_id]['qty']==0:
  print("Out of Stocks!")
elif record[up_prod_id]['qty']>= up_prod_qty:
  record[up_prod_id] ['qty']=record[up_prod_id]['qty']-up_prod_qty  
else:
  "Product is not Available"
  
myrecord=json.dumps(record)

fd=open("record2.json",'w')
fd.write(myrecord)
fd.close()

record



"""# **Purchase**"""



ui_prod_id=str(input("Enter the product id:"))
ui_prod_qty=int(input("Enter the product quantity:"))

if record[ui_prod_id]['qty']==0:
  print("Out of Stocks!")
elif record[ui_prod_id]['qty']>= ui_prod_qty:
  record[ui_prod_id] ['qty']=record[ui_prod_id]['qty']-ui_prod_qty  
else:
  "Product is not Available"

print("Product : ",record[ui_prod_id]['name'])
print("Product Quantity : ",ui_prod_qty) 
print("Price : ",record[ui_prod_id]['price'])
print("Bill Amount : ",record[ui_prod_id]['price']*ui_prod_qty) 
  
myrecord=json.dumps(record)

fd=open("record2.json",'w')
fd.write(myrecord)
fd.close()

record

"""# **Sales**"""

sales = {1 : {'prod_id':ui_prod_id,'prod_name':record[ui_prod_id]['name'],'prod_qty':ui_prod_qty,'prod_price':record[ui_prod_id]['price']*ui_prod_qty }}

mysales=json.dumps(sales)

fd=open("sales.json",'w')
fd.write(mysales)
fd.close()

fd = open('sales.json','r')
txt=fd.read()
fd.close()

sales=json.loads(txt)

sales

#Adding items to sales

ui_prod_id=str(input("Enter the product id:"))
ui_prod_qty=int(input("Enter the product quantity:"))

if record[ui_prod_id]['qty']==0:
  print("Out of Stocks!")
elif record[ui_prod_id]['qty']>= ui_prod_qty:
  record[ui_prod_id] ['qty']=record[ui_prod_id]['qty']-ui_prod_qty  
else:
  "Product is not Available"

print("Product : ",record[ui_prod_id]['name'])
print("Product Quantity : ",ui_prod_qty) 
print("Price : ",record[ui_prod_id]['price'])
print("Bill Amount : ",record[ui_prod_id]['price']*ui_prod_qty) 
  
myrecord=json.dumps(record)

fd=open("record2.json",'w')
fd.write(myrecord)
fd.close()

sales_id=int(input("Enter the sales id : "))
sales[sales_id]={'prod_id':ui_prod_id,'prod_name':record[ui_prod_id]['name'],'prod_qty':ui_prod_qty,'prod_price':record[ui_prod_id]['price']*ui_prod_qty}

mysales=json.dumps(sales)

fd=open("sales.json",'w')
fd.write(mysales)
fd.close()

sales



ui_prod_id=str(input("Enter the product id:"))
ui_prod_qty=int(input("Enter the product quantity:"))

if record[ui_prod_id]['qty']==0:
  print("Out of Stocks!")
elif record[ui_prod_id]['qty']>= ui_prod_qty:
  record[ui_prod_id] ['qty']=record[ui_prod_id]['qty']-ui_prod_qty  
else:
  "Product is not Available"

print("Product : ",record[ui_prod_id]['name'])
print("Product Quantity : ",ui_prod_qty) 
print("Price : ",record[ui_prod_id]['price'])
print("Bill Amount : ",record[ui_prod_id]['price']*ui_prod_qty) 
  
myrecord=json.dumps(record)

fd=open("record2.json",'w')
fd.write(myrecord)
fd.close()

sales_id=int(input("Enter the sales id : "))
sales[sales_id]={'prod_id':ui_prod_id,'prod_name':record[ui_prod_id]['name'],'prod_qty':ui_prod_qty,'Prod_price':record[ui_prod_id]['price']*ui_prod_qty}

mysales=json.dumps(sales)

fd=open("sales.json",'w')
fd.write(mysales)
fd.close()

record

sales

fd = open('sales.json','r')
txt=fd.read()
fd.close()

sales=json.loads(txt)